<?php 
//分页配置
$GLOBALS["wl_page"]["product"]=6;
$GLOBALS["wl_page"]["solution"]=6;
$GLOBALS["wl_page"]["anli"]=6;
$GLOBALS["wl_page"]["news"]=6;
$GLOBALS["wl_page"]["brand"]=30;
$GLOBALS["wl_page"]["message"]=5;
$GLOBALS["wl_page"]["search"]=6;
//数据库配置
$GLOBALS["wl_db"]["hostname"]="localhost";
$GLOBALS["wl_db"]["username"]="root";
$GLOBALS["wl_db"]["password"]="root";
$GLOBALS["wl_db"]["database"]="cicms";
//水印信息配置
$GLOBALS["wl_water"]["action"]=false;
$GLOBALS["wl_water"]["min_image_w"]=300;
$GLOBALS["wl_water"]["min_image_h"]=198;
//编辑器远程图片自动下载
$GLOBALS["wl_down"]["action"]=true;
$GLOBALS["wl_down"]["max_image_w"]=600;
//搜索引擎链接提交
$GLOBALS["wl_url"]["baidu"]="";
//调试信息配置
$GLOBALS["wl_ts"]["db_debug"]=false;
$GLOBALS["wl_ts"]["db_debug_file"]=false;
$GLOBALS["wl_ts"]["error"]=false;
$GLOBALS["wl_ts"]["cache"]=false;

?>